### ISSUE TITLE
is_playing() function JSON deserializer throws "IncompleteInput" errors intermittenly

### ISSUE THREAD

**Issue by antdicarlo** [FinianLandes/SpotifyEsp32#15] opened 2024-10-05 01:09 UTC
While playing around with this library I noticed that the getCurrentArtistAndSong example code would randomly fail occasionally. I turned on debug and noticed that the response codes were still 200s but the values returned by the function had no data. I'm not sure why this may happen but according to the ArduinoJson docs its seems like maybe the deserializer is timing out somehow. I am running on a ESP-WROOM-32. Here is the code I am running

```
// #define DISABLE_PLAYER
// #define DISABLE_ALBUM
#define DISABLE_ARTIST
#define DISABLE_AUDIOBOOKS
#define DISABLE_CATEGORIES
#define DISABLE_CHAPTERS
#define DISABLE_EPISODES
#define DISABLE_GENRES
#define DISABLE_MARKETS
#define DISABLE_PLAYLISTS
#define DISABLE_SEARCH
#define DISABLE_SHOWS
// #define DISABLE_TRACKS
// #define DISABLE_USER
// #define DISABLE_SIMPLIFIED
#define DISABLE_WEB_SERVER


#include <Arduino.h>
#include <WiFi.h>
#include "SpotifyEsp32.h"

// WIFI
const char* SSID = "";
const char* PASSWORD = "";

// Spotify
const char* CLIENT_ID =
const char* CLIENT_SECRET = 
const char* REFRESH_TOKEN = 

//Create an instance of the Spotify class Optional: you can set the Port for the webserver the debug mode(This prints out data to the serial monitor) and number of retries
Spotify sp(CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, 80, true, 10);


// LED Status
const int ledPin = LED_BUILTIN;  // the number of the LED pin

// API Ping Throttle
const long interval = 1000; // (in milliseconds)


void setup() {
    Serial.println("Setting Up");

    pinMode(LED_BUILTIN, OUTPUT);

    Serial.begin(115200);
    connect_to_wifi();
    
    sp.begin();
    while(!sp.is_auth()){
        sp.handle_client();
    }
    Serial.println("Authenticated");
}

void loop() {
    Serial.println("");
    Serial.println("********************************");
    Serial.println("");

    if (!sp.is_playing()) {
      digitalWrite(ledPin, LOW);
      delay(interval*2); //  longer delay to recheck since most of the time we aren\'t listening
      return;
    }
    
    digitalWrite(ledPin, HIGH);
    delay(interval);
}

void connect_to_wifi(){
    WiFi.begin(SSID, PASSWORD);
    Serial.print("Connecting to WiFi...");
    while (WiFi.status() != WL_CONNECTED) {
        delay(1000);
        Serial.print(".");
    }
    Serial.printf("\nConnected to WiFi\n");
}
```

And here is an example of a good response followed by the problem response without actually changing if I was playing music or not:

```
18:08:28.821 -> ********************************
18:08:28.821 -> 
18:08:29.441 -> HTTP/1.1 200 OK

18:08:29.442 -> content-type: application/json; charset=utf-8

18:08:29.442 -> Content-Length: 5066

18:08:29.442 -> Filter: On
18:08:29.442 -> GET "me/player/currently-playing" Status: 200
18:08:29.474 -> Reply: {"is_playing":false}
18:08:31.443 -> 
18:08:31.482 -> ********************************
18:08:31.482 -> 
18:08:32.076 -> HTTP/1.1 200 OK

18:08:32.076 -> content-type: application/json; charset=utf-8

18:08:32.076 -> Content-Length: 5066

18:08:32.076 -> Filter: On
18:08:32.120 -> Error: IncompleteInput
18:08:32.120 -> GET "me/player/currently-playing" Status: 200
18:08:32.120 -> Reply: {}
```

**Comment by FinianLandes** [comment] 2024-10-06 10:27
Thank you for reporting that, ill look over it maybe i find something

**Comment by FinianLandes** [comment] 2024-10-06 10:42
I'm somewhat not able to reproduce your error running your code. What esp32 do you use and might it be that your wifi is not too fast?
for reference i used the esp-wroom-32 to test it
Also you could try to set the timeout  (line 800 and something in the .h file) to more than one second even though time outing should give you server timed out or something like that instead of nothing

**Comment by antdicarlo** [comment] 2024-10-06 18:10
I’m using an ESP-WROOM-32. I’m using the express-if ESP32 board manager on the arduino IDE and just running the exact code I linked above. Super strange 🤔. I also noticed certain songs gave me a higher error rate as weird as that is. Songs with two artists would also occasionally have a value of NULL for one of the artists. I didn’t get a chance to test if that was the value from the api JSON or from the JSON decoder after parsing/filtering.

**Comment by antdicarlo** [comment] 2024-10-06 18:11
Oops didn’t mean to close

**Comment by antdicarlo** [comment] 2024-10-08 01:53
So I played around for a little bit today and turned the filter off. I captured two back to back API responses and you can see one of them is missing half of the data for some reason... I tried googling information about this happening to others with the spotify API and wasn't able to find anyone else with the same issue... What's strange to me is that its valid JSON that was returned with a 200 status. That would mean its something server side? Maybe I'm getting rate limited at 1 call per second? I doubt I would be. Very strange, would love to hear your thoughts on this. 

Here is the good API response:
```
{"timestamp":1728350753698,"context":{"external_urls":{"spotify":"https://open.spotify.com/collection/tracks"},"href":"https://api.spotify.com/v1/me/tracks","type":"collection","uri":"spotify:user:anster123:collection"},"progress_ms":128847,"item":{"album":{"album_type":"album","artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/7AC976RDJzL2asmZuz7qil"},"href":"https://api.spotify.com/v1/artists/7AC976RDJzL2asmZuz7qil","id":"7AC976RDJzL2asmZuz7qil","name":"Yes","type":"artist","uri":"spotify:artist:7AC976RDJzL2asmZuz7qil"}],"available_markets":["AR","AU","AT","BE","BO","BR","BG","CA","CL","CO","CR","CY","CZ","DK","DO","DE","EC","EE","SV","FI","FR","GR","GT","HN","HK","HU","IS","IE","IT","LV","LT","LU","MY","MT","MX","NL","NZ","NI","NO","PA","PY","PE","PH","PL","PT","SG","SK","ES","SE","CH","TW","TR","UY","US","GB","AD","LI","MC","ID","JP","TH","VN","RO","IL","ZA","SA","AE","BH","QA","OM","KW","EG","MA","DZ","TN","LB","JO","PS","IN","KZ","MD","UA","AL","BA","HR","ME","MK","RS","SI","KR","BD","PK","LK","GH","KE","NG","TZ","UG","AG","AM","BS","BB","BZ","BT","BW","BF","CV","CW","DM","FJ","GM","GE","GD","GW","GY","HT","JM","KI","LS","LR","MW","MV","ML","MH","FM","NA","NR","NE","PW","PG","PR","WS","SM","ST","SN","SC","SL","SB","KN","LC","VC","SR","TL","TO","TT","TV","VU","AZ","BN","BI","KH","CM","TD","KM","GQ","SZ","GA","GN","KG","LA","MO","MR","MN","NP","RW","TG","UZ","ZW","BJ","MG","MU","MZ","AO","CI","DJ","ZM","CD","CG","IQ","LY","TJ","VE","ET","XK"],"external_urls":{"spotify":"https://open.spotify.com/album/78tN6vBPHHyNk4sZYnS5X4"},"href":"https://api.spotify.com/v1/albums/78tN6vBPHHyNk4sZYnS5X4","id":"78tN6vBPHHyNk4sZYnS5X4","images":[{"height":640,"url":"https://i.scdn.co/image/ab67616d0000b273fb00f7be0eca020bb5c05911","width":640},{"height":300,"url":"https://i.scdn.co/image/ab67616d00001e02fb00f7be0eca020bb5c05911","width":300},{"height":64,"url":"https://i.scdn.co/image/ab67616d00004851fb00f7be0eca020bb5c05911","width":64}],"name":"Fragile (Super Deluxe)","release_date":"1971-11-12","release_date_precision":"day","total_tracks":46,"type":"album","uri":"spotify:album:78tN6vBPHHyNk4sZYnS5X4"},"artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/7AC976RDJzL2asmZuz7qil"},"href":"https://api.spotify.com/v1/artists/7AC976RDJzL2asmZuz7qil","id":"7AC976RDJzL2asmZuz7qil","name":"Yes","type":"artist","uri":"spotify:artist:7AC976RDJzL2asmZuz7qil"}],"available_markets":["AR","AU","AT","BE","BO","BR","BG","CA","CL","CO","CR","CY","CZ","DK","DO","DE","EC","EE","SV","FI","FR","GR","GT","HN","HK","HU","IS","IE","IT","LV","LT","LU","MY","MT","MX","NL","NZ","NI","NO","PA","PY","PE","PH","PL","PT","SG","SK","ES","SE","CH","TW","TR","UY","US","GB","AD","LI","MC","ID","JP","TH","VN","RO","IL","ZA","SA","AE","BH","QA","OM","KW","EG","MA","DZ","TN","LB","JO","PS","IN","KZ","MD","UA","AL","BA","HR","ME","MK","RS","SI","KR","BD","PK","LK","GH","KE","NG","TZ","UG","AG","AM","BS","BB","BZ","BT","BW","BF","CV","CW","DM","FJ","GM","GE","GD","GW","GY","HT","JM","KI","LS","LR","MW","MV","ML","MH","FM","NA","NR","NE","PW","PG","PR","WS","SM","ST","SN","SC","SL","SB","KN","LC","VC","SR","TL","TO","TT","TV","VU","AZ","BN","BI","KH","CM","TD","KM","GQ","SZ","GA","GN","KG","LA","MO","MR","MN","NP","RW","TG","UZ","ZW","BJ","MG","MU","MZ","AO","CI","DJ","ZM","CD","CG","IQ","LY","TJ","VE","ET","XK"],"disc_number":1,"duration_ms":516245,"explicit":false,"external_ids":{"isrc":"USRH12302535"},"external_urls":{"spotify":"https://open.spotify.com/track/466C6kwoJHLUJ8VHG98hCY"},"href":"https://api.spotify.com/v1/tracks/466C6kwoJHLUJ8VHG98hCY","id":"466C6kwoJHLUJ8VHG98hCY","is_local":false,"name":"Roundabout - 2024 Remaster","popularity":50,"preview_url":"https://p.scdn.co/mp3-preview/f8b1ef91110798eb99ac7c30ae82cb6d0ae81b6f?cid=cdecbc2901ba4ae396e4d4e56fef634d","track_number":1,"type":"track","uri":"spotify:track:466C6kwoJHLUJ8VHG98hCY"},"currently_playing_type":"track","actions":{"disallows":{"resuming":true}},"is_playing":true}
```

and was immediately followed by:
```
{"timestamp":1728350753698,"context":{"external_urls":{"spotify":"https://open.spotify.com/collection/tracks"},"href":"https://api.spotify.com/v1/me/tracks","type":"collection","uri":"spotify:user:anster123:collection"},"progress_ms":128847,"item":{"album":{"album_type":"album","artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/7AC976RDJzL2asmZuz7qil"},"href":"https://api.spotify.com/v1/artists/7AC976RDJzL2asmZuz7qil","id":"7AC976RDJzL2asmZuz7qil","name":"Yes","type":"artist","uri":"spotify:artist:7AC976RDJzL2asmZuz7qil"}],"available_markets":["AR","AU","AT","BE","BO","BR","BG","CA","CL","CO","CR","CY","CZ","DK","DO","DE","EC","EE","SV","FI","FR","GR","GT","HN","HK","HU","IS","IE","IT","LV","LT","LU","MY","MT","MX","NL","NZ","NI","NO","PA","PY","PE","PH","PL","PT","SG","SK","ES","SE","CH","TW","TR","UY","US","GB","AD","LI","MC","ID","JP","TH","VN","RO","IL","ZA","SA","AE","BH","QA","OM","KW","EG","MA","DZ","TN","LB","JO","PS","IN","KZ","MD","UA","AL","BA","HR","ME","MK","RS","SI","KR","BD","PK","LK","GH","KE","NG","TZ","UG","AG","AM","BS","BB","BZ","BT","BW","BF","CV","CW","DM","FJ","GM","GE","GD","GW","GY","HT","JM","KI","LS","LR","MW","MV","ML","MH","FM","NA","NR","NE","PW","PG","PR","WS","SM","ST","SN","SC","SL","SB","KN","LC","VC","SR","TL","TO","TT","TV","VU","AZ","BN","BI","KH","CM","TD","KM","GQ","SZ","GA","GN","KG","LA","MO","MR","MN","NP","RW","TG","UZ","ZW","BJ","MG","MU","MZ","AO","CI","DJ","ZM","CD","CG","IQ","LY","TJ","VE","ET","XK"],"external_urls":{"spotify":"https://open.spotify.com/album/78tN6vBPHHyNk4sZYnS5X4"},"href":"https://api.spotify.com/v1/albums/78tN6vBPHHyNk4sZYnS5X4","id":"78tN6vBPHHyNk4sZYnS5X4","images":[{"height":640,"url":"https://i.scdn.co/image/ab67616d0000b273fb00f7be0eca020bb5c05911","width":640},{"height":300,"url":"https://i.scdn.co/image/ab67616d00001e02fb00f7be0eca020bb5c05911","width":300},{"height":64,"url":"https://i.scdn.co/image/ab67616d00004851fb00f7be0eca020bb5c05911","width":64}],"name":"Fragile (Super Deluxe)","release_date":"1971-11-12","release_date_precision":"day","total_tracks":46,"type":"album","uri":"spotify:album:78tN6vBPHHyNk4sZYnS5X4"},"artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/7AC976RDJzL2asmZuz7qil"},"href":"https://api.spotify.com/v1/artists/7AC976RDJzL2asmZuz7qil","id":"7AC976RDJzL2asmZuz7qil","name":"Yes","type":"artist","uri":"spotify:artist:7AC976RDJzL2asmZuz7qil"}],"available_markets":["AR","AU","AT","BE","BO","BR","BG","CA","CL","CO","CR","CY","CZ","DK","DO","DE","EC","EE","SV","FI","FR","GR","GT","HN","HK","HU","IS","IE","IT","LV","LT","LU","MY","MT","MX","NL","NZ","NI","NO","PA","PY","PE","PH","PL","PT","SG","SK","ES","SE","CH","TW","TR","UY","US","GB","AD","LI","MC","ID","JP","TH","VN","RO","IL","ZA","SA","AE","BH","QA","OM","KW","EG","MA","DZ","TN","LB","JO","PS","IN","KZ","MD","UA","AL","BA","HR","ME","MK","RS","SI","KR","BD","PK","LK","GH","KE","NG","TZ","UG","AG","AM","BS","BB","BZ","BT","BW","BF","CV","CW","DM","FJ","GM","GE","GD","GW","GY","HT","JM","KI","LS","LR","MW","MV","ML","MH","FM","NA","NR","NE","PW","PG","PR","WS","SM","ST","SN","SC","SL","SB","KN","LC","VC","SR","TL","TO","TT","TV","VU","AZ","BN","BI","KH","CM","TD","KM","GQ","SZ","GA","GN","KG","LA","MO","MR","MN","NP","RW","TG","UZ","ZW","BJ","MG","MU","MZ","AO","CI","DJ","ZM","CD","CG","IQ","LY","TJ","VE","ET","XK"],"disc_number":1,"duration_ms":516245,"explicit":false,"external_ids":{"isrc":"USRH12302535"},"external_urls":{"spotify":"https://open.spotify.com/track/466C6kwoJHLUJ8VHG98hCY"},"href":"https://api.spotify.com/v1/tracks/466C6kwoJHLUJ8VHG98hCY","id":"466C6kwoJHLUJ8VHG98hCY","is_local":false,"name":"Roundabout - 2024 Remaster","popularity":50,"preview_url":"https://p.scdn.co/mp3-preview/f8b1ef91110798eb99ac7c30ae82cb6d0ae81b6f?cid=cdecbc2901ba4ae396e4d4e56fef634d","track_number":1,"type":"track","uri":"spotify:track:466C6kwoJHLUJ8VHG98hCY"},"currently_playing_type":"track","actions":{"disallows":{"resuming":true}},"is_playing":true}
```

**Comment by antdicarlo** [comment] 2024-10-08 01:59
You can see the difference between the API calls here: https://www.diffchecker.com/dwrqg7ZH/

It seems as if the server cut the transaction short? I don't work with APIs a lot but is it normal for the server to terminate the operation early but still go out of the way to make the JSON valid?

**Comment by antdicarlo** [comment] 2024-10-08 02:04
One other weird factor is that the timestamp on the API calls is exactly the same yet the serial monitor shows timestamps of 18:27:14.372 followed by 18:27:16.423 🤔. I bet there can be some delay with the serial monitor but the point stands that they are indeed two different requests.

**Comment by FinianLandes** [comment] 2024-10-08 13:02
First of all thats very odd because i would have assumed aswell that either youd get the full thing or a corrupt thing, never happened to me before and i used the spotify API in a lot of projects in different languages and there id always get the full thing, nothing or something invalid but never half but valid.

About the timestamp thing that took me a long time to figure out but after contacting the spotify developers the timestamp does not contain the time of the request on the server side but the timestamp of when the playback was last changed(eg. next song, play/pause etc) thats really annoying but it seems that they mad it that way so you cant sync up things with their API.

**Comment by FinianLandes** [comment] 2024-10-15 07:02
Have you gotten any more ideas or maybe reasons causing this? otherwise ill close this as can't repro

**Comment by antdicarlo** [comment] 2024-10-17 07:07
Sorry I've been super busy, I'll probably play around more next month and try to figure out what's going on. Feel free to close in the meantime since you cant repro

**Comment by FinianLandes** [comment] 2024-10-17 09:11
No Problem feel free to open another one, if you want you can also contact me on discord there chatting is easier my name there is Chaerne

**Closed** 2024-10-17 09:11 UTC
